import { Kumbh_Sans } from "next/font/google";
import "@/styles/globals.css";

const kumbh_sans = Kumbh_Sans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "e-commerce-product-page",
  description: "Generated by Shadow",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={kumbh_sans.className}>{children}</body>
    </html>
  );
}
